name: Deploy Static Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Get S3 bucket name
      id: bucket
      run: |
        BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'example-aws-app') && contains(Name, 'website')].Name" --output text)
        echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

    - name: Sync to S3
      run: |
        aws s3 sync ./src/ s3://${{ steps.bucket.outputs.bucket_name }}/ --delete